# Graph Learning

# Sparse Matrices

In this lab, you will learn to use sparse matrices.

In [1]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [12]:
X_dense


array([[1, 1, 0, 0, 2],
       [1, 2, 2, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 2, 0, 1],
       [1, 1, 1, 1, 0],
       [0, 2, 0, 2, 0],
       [2, 1, 1, 0, 2],
       [1, 2, 2, 2, 1],
       [0, 1, 1, 2, 0],
       [2, 2, 2, 0, 1]])

In [16]:
np.unique(X_dense)

array([0, 1, 2])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [7]:
# number of non-zeros
X_csr.nnz

34

The data structure consists of 3 vectors:

In [24]:
X_csr.indices #rows of the matrix


array([0, 1, 4, 0, 1, 2, 3, 4, 0, 1, 2, 4, 0, 1, 2, 3, 1, 3, 0, 1, 2, 4,
       0, 1, 2, 3, 4, 1, 2, 3, 0, 1, 2, 4], dtype=int32)

In [9]:
X_csr.indptr # 3 - 0 = 3 (#non zero elements in the first row), 8-3 = 5 (non zero elements...second row)

array([ 0,  3,  8,  9, 12, 16, 18, 22, 27, 30, 34], dtype=int32)

In [10]:
X_csr.data

array([1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2,
       1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1])

## To do

* Can you find the number of non-zeros from these 3 vectors?


**answer:** 34 non zero elements, its possible by either computing the length of the `X_csr.data` or the len of `X_csr.indices` or getting the last element of the `indptr`
  
* What about the shape of the matrix?

**answer:** we can get the shape by doing max(X_csr.indices) + 1

In [23]:
len(X_csr.data)

34

In [25]:
max(X_csr.indices)+1

np.int32(5)

## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [26]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [27]:
X_dense

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 0]])

In [28]:
a = np.ones(n_col, dtype=int)

In [29]:
b = X.dot(a)

In [30]:
b

array([1, 1, 1, 2, 1, 2, 2, 2, 3, 2])

In [31]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [32]:
b

array([3, 5, 5, 4])

In [33]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [34]:
A

array([[0, 1],
       [0, 0],
       [1, 1],
       [1, 1]])

In [35]:
B

array([[1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 2],
       [2, 3],
       [0, 1]])

In [36]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [37]:
B

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 15 stored elements and shape (10, 2)>

In [38]:
B.toarray()

array([[1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 2],
       [2, 3],
       [0, 1]])

In [39]:
X.T.dot(X)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 14 stored elements and shape (4, 4)>

In [40]:
X.dot(X.T)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 62 stored elements and shape (10, 10)>

In [41]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [42]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 34 stored elements and shape (10, 5)>

In [43]:
Y = X > 1

In [44]:
Y

<Compressed Sparse Row sparse matrix of dtype 'bool'
	with 15 stored elements and shape (10, 5)>

In [45]:
Y.dot(np.ones(n_col, dtype=int))

array([2, 1, 1, 2, 3, 1, 2, 0, 1, 2])

In [46]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [47]:
Z = 2 * X + 5 * Y

In [48]:
Z

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 34 stored elements and shape (10, 5)>

In [49]:
Z.power(2)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 34 stored elements and shape (10, 5)>

## To do

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [ ]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [ ]:
X = sparse.csr_matrix(X_dense)

In [ ]:
indices = [2, 5, 6]

In [ ]:
X[indices]

In [ ]:
X[:, [1, 3]]

## To do 

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

## DIAG format

In [ ]:
D = sparse.diags(np.arange(10))

In [ ]:
D

In [ ]:
D.data

In [ ]:
D.nnz

In [ ]:
D = sparse.csr_matrix(D)

In [ ]:
D.data

In [ ]:
D.nnz

In [ ]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [ ]:
D.dot(X)

In [ ]:
D = sparse.diags(np.ones(4))

In [ ]:
X.dot(D)

## To do

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [ ]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [ ]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_coo

In [ ]:
X_coo.row

In [ ]:
X_coo.col

In [ ]:
X_coo.data

You can change the format:

In [ ]:
X_csr = X_coo.tocsr()

In [ ]:
X_csr

In [ ]:
X_csr.indices

In [ ]:
X_csr.indptr

In [ ]:
X_csr.data

In [ ]:
X_csr.tocoo()

You can directly load a CSR matrix from COO format:

In [ ]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_csr

Duplicate entries are not summed by default in the COO format (also in the CSR format in the last version of Scipy):

In [ ]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [ ]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_coo

In [ ]:
X_coo.nnz

In [ ]:
X_coo.toarray()

In [ ]:
X_coo.dot(np.ones(5, dtype=int))

In [ ]:
X_coo.data

In [ ]:
X_coo.sum_duplicates()

In [ ]:
X_coo

In [ ]:
X_coo.data

If data contain some zeros, these are coded as non-zeros by default:

In [ ]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 0]

In [ ]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_csr

In [ ]:
X_csr.eliminate_zeros()

In [ ]:
X_csr

## To do

Consider the following matrix:

In [ ]:
row = [1, 1, 2, 4, 2, 1]
col = [2, 2, 2, 0, 2, 2]
data = [1, 2, 3, 4, 0, 2]

X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))
X_csr.sum_duplicates()

* What is the number of non-zeros? 
* Check your answer using ``nnz``.